CREATE DATABASE db_company;

USE db_company;

CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY NOT NULL DEFAULT UUID(), 
    name VARCHAR(30) NOT NULL, 
    email VARCHAR(80) NOT NULL, 
    password VARCHAR(100) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);